-- Migration: cycling routes per city
-- One classic cycling route per city, generated by Doubao (火山方舟) at approval
-- time and curated by an admin before going public. Riders in the same city share
-- the same route (keyed by city_key), so we never generate twice for one place.
-- Safe to run once; guarded so re-running is a no-op.

BEGIN;

CREATE TABLE IF NOT EXISTS routes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- normalized lowercase "city, country" used for dedup/lookup, e.g. "la ciotat, france"
  city_key text UNIQUE NOT NULL,
  city text NOT NULL,
  country text,
  lat float8,
  lng float8,
  name text,                       -- route name, e.g. "Route des Crêtes Loop"
  distance_km float8,
  difficulty text CHECK (difficulty IN ('easy', 'moderate', 'hard')),
  description text,                -- short blurb in TRACKID voice
  -- ordered list of {name, lat, lng} the route passes through (3-6 points)
  waypoints jsonb NOT NULL DEFAULT '[]'::jsonb,
  source text NOT NULL DEFAULT 'doubao-ai',   -- 'doubao-ai' | 'manual'
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_routes_city_key ON routes (city_key);
CREATE INDEX IF NOT EXISTS idx_routes_status ON routes (status);

-- Row Level Security: public reads published routes only; service role bypasses RLS.
ALTER TABLE routes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can view published routes" ON routes;
CREATE POLICY "Public can view published routes"
  ON routes FOR SELECT
  USING (status = 'published');

COMMIT;
